#!/bin/bash

sudo -v # ask for password only at the beginning

brew update
brew upgrade

brew install bash
echo "/usr/local/bin/bash" | sudo tee -a /etc/shells
chsh -s /usr/local/bin/bash

brew install git
brew install node
brew install wget
brew install ondir
brew install hub

brew cask install caskroom/versions/sublime-text3
brew cask install atom
brew cask install webstorm
brew cask install iterm2
brew cask install gitx
brew cask install xscope
brew cask install mou
brew cask install alfred
brew cask install transmit

brew cask install yandex
brew cask install chromium
brew cask install firefox

brew cask install adium
brew cask install skype
brew cask install teamviewer
brew cask install yandexdisk
brew cask install dropbox
brew cask install evernote
brew cask install transmission
brew cask install vlc
brew cask install appzapper
brew cask install imageoptim
brew cask install spectacle

brew cleanup
