#!/bin/bash

sudo -v # ask for password only at the beginning

brew update
brew upgrade

brew install bash
echo "/usr/local/bin/bash" | sudo tee -a /etc/shells
chsh -s /usr/local/bin/bash

brew install git \
    nvm \
    wget \
    ondir \
    hub \
    ccat \
    ag

brew cask install caskroom/versions/sublime-text3 \
	atom \
	webstorm \
	iterm2 \
	gitx \
	xscope \
	mou \
	transmit

brew cask install  yandex \
	chromium \
	firefox

brew cask install adium \
	skype \
	teamviewer \
	yandexdisk \
	dropbox \
	evernote \
	transmission \
	vlc \
	appzapper \
	imageoptim \
	imagealpha \
	spectacle \
	apptivate \
	clipmenu-dev \
	beardedspice

brew cleanup
