set -g default-terminal "tmux-256color"
set -as terminal-overrides ",*:Tc"

set -g mouse on
set -sg escape-time 0
set -g history-limit 50000
set -g focus-events on
set -g renumber-windows on

# Для прокидывания актуального ssh-сокета через tmux.
# @see ssh/rc
# @see https://werat.github.io/2017/02/04/tmux-ssh-agent-forwarding.html
# @see https://gist.github.com/jvkersch/e7ef80dea675524d332f
setenv -g SSH_AUTH_SOCK $HOME/.ssh/ssh_auth_sock
set -g update-environment -r
